### ISSUE TITLE
one issues

### ISSUE THREAD

**Issue by HolleDeng** [google/stereo-magnification#1]
hi, i want to say one issues.

i try to run this program,
in  stereomag/loader.py ,  178 line ,   
"  sequences_with_images = sequence_with_images.map"
I suspect something is wrong here.

Is it  "sequence_with_images"  not miss written?

Your favorite fans! Looking forward to your reply.!

**Comment by snaves** [comment]
Thanks for the comment. This has been fixed in this commit: https://github.com/google/stereo-magnification/commit/d816db2e2ba4ea66345885d15681f6b02c548b04
