### ISSUE TITLE
MPI without camera parameters?

### ISSUE THREAD

**Issue by PuneetKohli** [google/stereo-magnification#15]
If we do not have the Camera parameters, and just a rectified stereo pair (no knowledge of where the stereo pair came from) -- what would the best values be to use for `fx` and `fy`? 

Or is there a modification to the network/model we can make that assumes the cameras are rectified.

**Comment by danperazzo** [comment]
I have the same issue: is the camera parameters necessary to estimate a MPI from a stereo pair?

**Comment by snaves** [comment]
If you have a stereo pair, then you could probably get away with using a nominal set of camera parameters where you just translate the camera some distance in the x-direction. See the 'twain' example to see how to do this: https://github.com/google/stereo-magnification/blob/master/examples/twain/command_line.txt

In that example, we specify the focal length with the --fx and --fy parameters. If you don't know the focal length, you could probably get away with making a guess.

**Comment by PuneetKohli** [comment]
Thanks for your reply Dr. Snavely!

**Comment by danperazzo** [comment]
Thanks Dr. Snavely :))
