### ISSUE TITLE
Derivation of formula (2), inverse homography

### ISSUE THREAD

**Issue by zikuicai** [google/stereo-magnification#19]
Can anyone help explain the derivation of formula (2) in the paper? 
<img width="544" alt="Screen Shot 2019-08-05 at 5 35 46 PM" src="https://user-images.githubusercontent.com/22699667/62503091-7d3bc000-b7a7-11e9-857e-cb320220730e.png">
I understand the equation (13.2) from  [Hartley and Zisserman 2003]:
![image](https://user-images.githubusercontent.com/22699667/62503527-6c8c4980-b7a9-11e9-9286-46cf987eed2d.png)
However, I still find it hard to understand what's in the parentheses of formula (2), especially the denominator.
Can anyone help? Many thanks in advance.

**Comment by iszihan** [comment]
I have the same confusion, did you find an answer to this?

**Comment by zikuicai** [comment]
Yes. You can use Sherman-Morrison formula to find the inverse homography.

**Comment by Jaswers** [comment]
![image](https://user-images.githubusercontent.com/15664493/106240374-2188b080-623f-11eb-9f17-2fbc744933e6.png)
Sherman-Morrison formula
