### ISSUE TITLE
Shifting image2 to image1

### ISSUE THREAD

**Issue by phongnhhn92** [google/stereo-magnification#28]
Hello guys, I just start reading the code of this repo and I can see that the first processing step is to shift source image(img2) to reference image(image1) by xshift and yshift. My question is: why we have to do that ? I have tried to find the reason on the paper but I found no explanation.

Also, do you shift img2 during training or is this just for the testing/evaluation ?

**Comment by reyet** [comment]
It's only necessary if you want to run on input images where the principal point is different between the two inputs. This is the case with some lightfield camera data, for example. We don't use it with the RealEstate10K data or during training.

**Comment by phongnhhn92** [comment]
Thanks @reyet ! I will close this now.
