### ISSUE TITLE
how to run the model on a single image pair?

### ISSUE THREAD

**Issue by suljaxm** [google/stereo-magnification#4]
I type the command on the terminal, as follows   “python mpi_from_images.py  image1=./XXX image2=./XXXX” , but it is error.
Could you please help me.  Also I can't use any other code....

**Comment by olivertai** [comment]
Try
python mpi_from_images.py \
--image1 /path_to_image1 \
--image2 /path_to_image2 \
--output_dir ./tmp/result

**Comment by suljaxm** [comment]
Thank you for your prompt reply, but when I tried your way, it was still error.  
The error :

Traceback (most recent call last):
  File "mpi_from_images.py", line 64, in <module>
    flags.DEFINE_list(
AttributeError: module 'tensorflow.python.platform.flags' has no attribute 'DEFINE_list'

**Comment by olivertai** [comment]
I have encountered this problem too. It seems that we don't have attribute "DEFINE_list".
Try
changing "DEFINE_list" to "DEFINE_string", and use another list to read the values
`render_list = [float(x) for x in flags.FLAGS.render_multiples.split(',')]`
Then replace the original usage in the code.
around line 220:
`max_multiple = max(abs(float(m)) for m in render_list)`
around line 280:
`for multiple in render_list:`
And try running again.

**Comment by suljaxm** [comment]
It's ok, thanks so much to you.

**Comment by snaves** [comment]
Thanks for the feedback -- note that this should now be fixed in https://github.com/google/stereo-magnification/commit/3eb2f9e7b3447e1fd03233dcb69578235e2c5376. 

Please let us know if you still see a problem related to this issue.

**Comment by suljaxm** [comment]
ok
