### ISSUE TITLE
about the random_seed

### ISSUE THREAD

**Issue by textstorm** [google/stereo-magnification#6]
I download the pretrained model, and run test.py, but I got the same src_1 and tgt_image. This means that the ground truth(tgt_image) is the same as src_1 image (have the same timestamp). I think this may be a problem with random seeds.
My python is 2.7, tensorflow 1.10-gpu

**Comment by snaves** [comment]
You might have to explain more about what you are doing, e.g., provide the command line you ran that gave you the results that seem to have a problem.
