### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by Gpoxolcku** [google/stereo-magnification#7]
Hi, friend!
Am I getting it right that the "render" flag's purpose is to allow output of rendered extrapolated stereopair images? No matter of the "render_multiples" values, the rendering result is the cropped reference image. Here's an example of the command I use to launch the tool:
`
python mpi_from_images.py
    --image1=/path/to/left.png
    --image2=/path/to/right.png 
    --output_dir=./output/
    --render_multiples=10
    --render=True
`
Thanks in advance!

**Comment by Gpoxolcku** [comment]
Thank you for your reply! Also I'd like to mention that when I try to render multiple images, it fails with (likely) out-of-memory error (I use Google Colab GPU). Is there any possible way to fix it?

**Comment by snaves** [comment]
Interesting -- I haven't tested on a Colab GPU. I guess the backup is to render a single image and call the binary multiple times. However, I am unsure of why you would run out of memory, though I will give it some thought. Please feel free to propose a fix if you uncover the issue.

**Comment by BaileyRobbins** [comment]
Can you explain what the offset values in render_multiples mean?  Are they the offsets in world coordinates from camera 0?

**Comment by FangGet** [comment]
@Gpoxolcku  I came up with an error like "Graphdef cannot be larger than 2GB in tensorflow", if it's also yours, just add "tf.reset_default_graph" after sess.run will fix this problem.

**Comment by noobtoob4lyfe** [comment]
> 
> 
> Note also that if you want to render multiple images, you can provide multiple offsets in the "--render_multiples" argument (e.g, "--render_multiples="-10,0,10").

Hello.  I was googeling around for a way to try out this code and I saw your comment about a Colab notebook.  Is this Google Colab Notebook still available?  May I try it out?  Thanks in advance.
