### ISSUE TITLE
Sample images for mpi_from_images.py

### ISSUE THREAD

**Issue by BaileyRobbins** [google/stereo-magnification#8]
Hello,
I was wondering if you could provide sample images and commandline for this script.  I am running on my own images and I'm not sure if the output is as expected or if there is an error in commandline.  I think this would be really helpful, thanks in advance!

**Comment by snaves** [comment]
We have now provided an example in the [examples subdirectory](https://github.com/google/stereo-magnification/tree/master/examples). We will be adding additional examples soon.

**Comment by BaileyRobbins** [comment]
Thank you, the example is working well for me.
