### ISSUE TITLE
Units for x/y/z offset

### ISSUE THREAD

**Issue by BaileyRobbins** [google/stereo-magnification#9]
Hi, 

I'm not able to generate the expected output from sample images I have.  I suspect my camera offsets are incorrect.  May I know:
1. What are the units, are they in meters?
2. Is there any limitation (max/min) for the x offset?

Thanks!

**Comment by snaves** [comment]
The units of --xoffset/yoffset/zoffset are not explicitly in meters, but should make sense relative to the near and far plane distances, which are 1 and 100. For instance, if your cameras are 2cm apart in the x-direction and the closest objects are 1.1m from the camera, then --xoffset=0.02 should work fine with the default plane distances. Note that if you specify the camera poses with --pose1 and --pose2, then --xoffset/yoffset/zoffset have a different meaning (*output* camera offsets from the reference view, with units that have the same magnitude as the camera poses).

**Comment by PuneetKohli** [comment]
Are the near and far plane distances of 1 and 100 in meters?

Let's say I have a camera with a baseline of 1.35cm, should I just use 0.0135 in all cases? Is there any special considerations I need to make based on the image content?

(Assuming cameras are rectified)

Thanks.
